"""
title: CNAP RAG Report Reader
id: cnap_rag_report_reader
version: 1.0.0
description: >
    Reads the latest automated security analysis report generated by the RAG Agent
    and injects it into the LLM context so users can ask questions about it.
    Triggers on phrases like "latest report", "last analysis", "recent findings".
author: CNAP Security Team
license: Apache-2.0
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# Keywords that trigger loading the latest report
_REPORT_QUERY_KEYWORDS = [
    "latest report", "last report", "recent report",
    "latest analysis", "last analysis", "recent analysis",
    "latest findings", "recent findings",
    "what does the report say", "show me the report",
    "summarize the report", "summary of findings",
    "what was found", "what threats", "what anomalies",
]

# Maximum character length of report to include in context
_MAX_REPORT_CHARS = 8000


class Filter:
    """RAG report reader filter for Open WebUI.

    When the user asks about the latest security analysis, this filter reads
    the most recent report from disk and injects it as LLM context.
    """

    class Valves(BaseModel):
        """Configuration valves — set in Open WebUI Admin Panel."""

        REPORTS_DIR: str = Field(
            default="/app/backend/data/outputs",
            description="Directory where RAG agent saves analysis reports",
        )
        MAX_REPORT_AGE_HOURS: int = Field(
            default=4,
            description="Warn if latest report is older than this many hours",
        )
        ENABLED: bool = Field(
            default=True,
            description="Enable or disable this filter",
        )

    def __init__(self) -> None:
        self.valves = self.Valves(
            REPORTS_DIR=os.environ.get("OUTPUT_DIR", "/app/backend/data/outputs"),
        )

    def inlet(self, body: dict, user: dict | None = None) -> dict:  # noqa: ARG002
        """Pre-process the user message before sending to the LLM.

        If the message asks about the latest report, reads the most recent
        analysis file and injects it into the LLM context.

        Args:
            body: Open WebUI chat request body.
            user: Current user information (not used).

        Returns:
            Modified body with report context injected, or original body.
        """
        if not self.valves.ENABLED:
            return body

        messages = body.get("messages", [])
        if not messages:
            return body

        # Get the most recent user message
        user_message = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                content = msg.get("content", "")
                user_message = content if isinstance(content, str) else str(content)
                break

        if not _is_report_query(user_message):
            return body

        # Find and read the latest report
        report_context = self._load_latest_report()
        if not report_context:
            return body

        body = _inject_context(body, report_context)
        logger.info("Injected latest RAG report into LLM context")
        return body

    def _load_latest_report(self) -> str | None:
        """Find and read the most recent analysis report.

        Returns:
            Formatted report context string, or None if no report found.
        """
        reports_dir = Path(self.valves.REPORTS_DIR)

        if not reports_dir.exists():
            logger.warning("Reports directory not found: %s", reports_dir)
            return None

        # Find all JSON report files (prefer JSON for structured data)
        json_reports = sorted(reports_dir.glob("analysis_*.json"), reverse=True)
        txt_reports = sorted(reports_dir.glob("analysis_*.txt"), reverse=True)

        # Try JSON first for richer metadata
        if json_reports:
            return self._format_json_report(json_reports[0])
        elif txt_reports:
            return self._format_txt_report(txt_reports[0])
        else:
            logger.warning("No analysis reports found in %s", reports_dir)
            return None

    def _format_json_report(self, report_path: Path) -> str | None:
        """Format a JSON report for LLM context injection.

        Args:
            report_path: Path to the JSON report file.

        Returns:
            Formatted context string or None on error.
        """
        try:
            data = json.loads(report_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.error("Failed to read JSON report %s: %s", report_path, exc)
            return None

        timestamp = data.get("timestamp", "unknown")
        log_count = data.get("log_count", "unknown")
        duration = data.get("duration_seconds", 0)
        analysis = data.get("analysis", "No analysis content")
        citations = data.get("citations", [])

        # Check report age
        age_warning = _check_report_age(timestamp, self.valves.MAX_REPORT_AGE_HOURS)

        # Truncate analysis if too long
        if len(analysis) > _MAX_REPORT_CHARS:
            analysis = analysis[:_MAX_REPORT_CHARS] + "\n... [truncated — report continues]"

        lines = [
            "## Latest CNAP AI Security Analysis Report",
            f"Generated: {timestamp}",
            f"Logs analyzed: {log_count} events | Analysis duration: {duration:.1f}s",
        ]

        if age_warning:
            lines.append(f"⚠️  {age_warning}")

        if citations:
            lines.append(
                "Knowledge base sources cited: "
                + ", ".join(c.get("source", "") for c in citations[:5])
            )

        lines.append("")
        lines.append("### Analysis:")
        lines.append(analysis)
        lines.append("")
        lines.append(
            "--- End of report ---\n"
            "You may ask follow-up questions about specific findings, threats, or recommendations."
        )

        return "\n".join(lines)

    def _format_txt_report(self, report_path: Path) -> str | None:
        """Format a plain-text report for LLM context injection.

        Args:
            report_path: Path to the .txt report file.

        Returns:
            Formatted context string or None on error.
        """
        try:
            content = report_path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            logger.error("Failed to read text report %s: %s", report_path, exc)
            return None

        if len(content) > _MAX_REPORT_CHARS:
            content = content[:_MAX_REPORT_CHARS] + "\n... [truncated]"

        return (
            f"## Latest CNAP AI Security Analysis Report\n"
            f"File: {report_path.name}\n\n"
            f"{content}\n\n"
            f"--- End of report ---\n"
            f"You may ask follow-up questions about specific findings."
        )


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _is_report_query(message: str) -> bool:
    """Check if the user message is asking about the latest analysis report.

    Args:
        message: User message text.

    Returns:
        True if the message is a report query.
    """
    msg_lower = message.lower()
    return any(kw in msg_lower for kw in _REPORT_QUERY_KEYWORDS)


def _check_report_age(timestamp_str: str, max_age_hours: int) -> str | None:
    """Return a warning string if the report is older than expected.

    Args:
        timestamp_str: ISO 8601 timestamp string from the report.
        max_age_hours: Maximum acceptable report age in hours.

    Returns:
        Warning string or None if age is acceptable.
    """
    try:
        from datetime import datetime, timezone  # noqa: PLC0415

        report_time = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
        now = datetime.now(timezone.utc)
        age_hours = (now - report_time).total_seconds() / 3600
        if age_hours > max_age_hours:
            return (
                f"This report is {age_hours:.1f} hours old. "
                f"The RAG agent should generate a new report every {max_age_hours} hours. "
                f"Check `docker compose logs rag-agent` if reports are not being generated."
            )
    except (ValueError, AttributeError):
        pass
    return None


def _inject_context(body: dict, context: str) -> dict:
    """Inject context text as a system message.

    Args:
        body: Open WebUI request body.
        context: Context text to inject.

    Returns:
        Modified body.
    """
    messages = body.get("messages", [])
    context_message = {"role": "system", "content": context}

    if messages and messages[0].get("role") == "system":
        messages.insert(1, context_message)
    else:
        messages.insert(0, context_message)

    body["messages"] = messages
    return body
