"""
CNAP AI SIEM Copilot — Report Viewer Dashboard

A lightweight Flask application that displays the automated security analysis
reports generated by the RAG Agent. Provides a read-only view of reports
with sorting, filtering, and a clean UI.

Run:
    gunicorn -b 0.0.0.0:5000 app:app
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, jsonify, render_template
from flask import Response as FlaskResponse

# Configure logging
logging.basicConfig(
    level=getattr(logging, os.environ.get("LOG_LEVEL", "INFO").upper(), logging.INFO),
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# Report directory (read-only volume mount from rag-agent output)
OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "/app/data/outputs"))

# Maximum number of reports to list
MAX_REPORTS = 50


def _get_reports() -> list[dict]:
    """Scan the output directory and return report metadata sorted by newest first.

    Returns:
        List of report metadata dicts.
    """
    if not OUTPUT_DIR.exists():
        logger.warning("Output directory not found: %s", OUTPUT_DIR)
        return []

    reports = []
    for json_file in sorted(OUTPUT_DIR.glob("analysis_*.json"), reverse=True)[:MAX_REPORTS]:
        try:
            data = json.loads(json_file.read_text(encoding="utf-8"))
            reports.append({
                "id": json_file.stem,
                "filename": json_file.name,
                "timestamp": data.get("timestamp", "unknown"),
                "log_count": data.get("log_count", 0),
                "duration_seconds": round(data.get("duration_seconds", 0), 1),
                "rag_enabled": data.get("rag_enabled", False),
                "citation_count": len(data.get("citations", [])),
                "analysis_preview": data.get("analysis", "")[:300] + "...",
            })
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Skipping malformed report %s: %s", json_file.name, exc)
            continue

    return reports


def _get_report(report_id: str) -> dict | None:
    """Load a single report by its ID (filename stem).

    Args:
        report_id: Report ID (e.g., 'analysis_20241215_120000').

    Returns:
        Full report data dict, or None if not found.
    """
    json_path = OUTPUT_DIR / f"{report_id}.json"
    txt_path = OUTPUT_DIR / f"{report_id}.txt"

    if not json_path.exists():
        return None

    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        if txt_path.exists():
            data["text_report"] = txt_path.read_text(encoding="utf-8", errors="replace")
        return data
    except (json.JSONDecodeError, OSError) as exc:
        logger.error("Failed to read report %s: %s", report_id, exc)
        return None


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index() -> str:
    """Main dashboard page — list all reports.

    Returns:
        Rendered HTML page.
    """
    reports = _get_reports()
    last_updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return render_template(
        "index.html",
        reports=reports,
        last_updated=last_updated,
        output_dir=str(OUTPUT_DIR),
    )


@app.route("/report/<report_id>")
def report_detail(report_id: str) -> str | tuple[str, int]:
    """Individual report detail page.

    Args:
        report_id: Report ID from the URL path.

    Returns:
        Rendered HTML page, or 404 error.
    """
    # Sanitize to prevent path traversal
    safe_id = Path(report_id).name
    if safe_id != report_id or "/" in report_id or ".." in report_id:
        return render_template("index.html", error="Invalid report ID", reports=[]), 400

    data = _get_report(safe_id)
    if data is None:
        return render_template("index.html", error="Report not found", reports=_get_reports()), 404

    return render_template("index.html", report=data, reports=_get_reports())


@app.route("/api/reports")
def api_reports() -> FlaskResponse:
    """REST API endpoint — return report list as JSON.

    Returns:
        JSON response with reports list.
    """
    return jsonify({"reports": _get_reports()})


@app.route("/api/reports/<report_id>")
def api_report_detail(report_id: str) -> FlaskResponse | tuple[FlaskResponse, int]:
    """REST API endpoint — return single report as JSON.

    Args:
        report_id: Report ID from the URL path.

    Returns:
        JSON response with report data, or 404 error.
    """
    safe_id = Path(report_id).name
    if safe_id != report_id:
        return jsonify({"error": "Invalid report ID"}), 400

    data = _get_report(safe_id)
    if data is None:
        return jsonify({"error": "Report not found"}), 404

    return jsonify(data)


@app.route("/health")
def health() -> FlaskResponse:
    """Health check endpoint for Docker health checks.

    Returns:
        JSON response with service status.
    """
    report_count = len(list(OUTPUT_DIR.glob("analysis_*.json"))) if OUTPUT_DIR.exists() else 0
    return jsonify({
        "status": "ok",
        "report_count": report_count,
        "output_dir": str(OUTPUT_DIR),
        "output_dir_exists": OUTPUT_DIR.exists(),
    })


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
